"""Revision ID: c55d95de37f2
Revises: e881f41c3409
Create Date: 2026-05-07 08:00:40.373304
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55d95de37f2'
down_revision: Union[str, None] = 'e881f41c3409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('max_appointments_monthly', sa.Integer(), nullable=True),
    sa.Column('max_active_services', sa.Integer(), nullable=True),
    sa.Column('max_staff', sa.Integer(), nullable=True),
    sa.Column('allows_advanced_reminders', sa.Boolean(), nullable=True),
    sa.Column('allows_analytics', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_telegram_user_id'), ['telegram_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('telegram_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(), nullable=True),
    sa.Column('bot_token_masked', sa.String(), nullable=True),
    sa.Column('bot_username', sa.String(), nullable=True),
    sa.Column('bot_name', sa.String(), nullable=True),
    sa.Column('bot_description', sa.String(), nullable=True),
    sa.Column('bot_short_description', sa.String(), nullable=True),
    sa.Column('bot_profile_photo_path', sa.String(), nullable=True),
    sa.Column('use_global_bot', sa.Boolean(), nullable=True),
    sa.Column('bot_status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('services_message', sa.Text(), nullable=True),
    sa.Column('ask_date_message', sa.Text(), nullable=True),
    sa.Column('ask_time_message', sa.Text(), nullable=True),
    sa.Column('confirm_message', sa.Text(), nullable=True),
    sa.Column('cancel_message', sa.Text(), nullable=True),
    sa.Column('unavailable_message', sa.Text(), nullable=True),
    sa.Column('allow_cancellation', sa.Boolean(), nullable=True),
    sa.Column('show_prices', sa.Boolean(), nullable=True),
    sa.Column('show_duration', sa.Boolean(), nullable=True),
    sa.Column('bot_token_hint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_configs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_configs_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_foreign_key('fk_conversations_client_id', 'clients', ['client_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opening_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key('fk_tenants_plan_id', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key('fk_users_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenants_plan_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.alter_column('owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('plan_id')
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')
        batch_op.drop_column('slug')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('description')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('description')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_client_id', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('channel')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('telegram_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_configs_id'))

    op.drop_table('telegram_configs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_clients_telegram_user_id'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))

    op.drop_table('clients')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_id'))

    op.drop_table('plans')
    # ### end Alembic commands ###

